name: Static Map Maker
description: "Create a Bing static map, Google static map, Mapbox static map, MapQuest static map, a HERE static map, a CartoDB static map, or a Yandex static map. Type in a location, customize, and get the map."
url: http://staticmapmaker.com
#url: http://localhost:4000
permalink: /:title/

port: 4000
host: 127.0.0.1

# these will rotate
mapquestKey: HkQT4BGfQ9clGrwhLknjPxeF08UZ3k9K
bingKey: Ah12kIOAYzmW3ONiCcYEImWIp2xL8pwMXEvlOjhzjLRhjBBOCgBygJe4PHOY_aKU
hereappid: Aa1YIIyNYjkb6oaXEBL4
herecodeid: pVymqwwjz2o0icg1RF78OQ

exclude:
- vendor
- .sass-cache
- CNAME
- README.md
- Gemfile
- node_modules
- package.json
- test

gems:
- jekyll-sitemap
- jekyll-redirect-from
- jemoji

angularjs: 1.5.5
jquery: 2.2.3

# adsense
client: ca-pub-5924879737462180
slot: 3966465755

sass:
 style: :compressed

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "page"
